name: test1

env:
  one_target: one
  two_target: two
  one: one1
  two: two2

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'one'
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest
    env:
      target: ${{github.event.inputs.name}}_target
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson( format('["{0}"]', github.event.inputs.name) ) }}
    steps:
    - name: Send greeting
      env:
        NAME: ${{ env[matrix.target] }}
      run: echo "Hello ${{ env.target }}"
