name: test1

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest
    env:
      ONE: ${{github.event.inputs.name}}${{'-TARGET'}}

    steps:
    - name: Send greeting
      env:
        TWO: ${{env.ONE}}
      run: echo "Hello ${{ env.TWO }}"
