name: Upload Commit Hash to S3

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create commit hash file
        run: |
          echo "${{ github.sha }}" > commit-hash.txt

      - name: Upload to S3
        run: |
          aws s3 cp commit-hash.txt s3://${{ secrets.S3_BUCKET }}/commit-hash.txt 